disabled_rules:
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - line_length
  - trailing_whitespace
  - large_tuple
  - function_parameter_count
  - identifier_name
  - unused_setter_value
  - control_statement

opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_end_indentation
  - closure_spacing
  - first_where
  - nimble_operator
  - operator_usage_whitespace
  - overriden_super_call
  - redundant_nil_coalescing
  - multiline_parameters
  - extension_access_modifier
  - implicit_return
  - protocol_property_accessors_order

  # TODO: Add in `missing_docs` after we backfill documentation
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods  

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# empty_count: warning
type_name:
  min_length: 3
  max_length: 40
  excluded: iPhone

variable_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - URL
    - url
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
